version: '3.9'

services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"

  diana-db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "34567:34567"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark
      POSTGRES_DB: benchmark
    ports:
      - "5432:5432"
